version: '3.8'
services:
    api:
        restart: always
        hostname: api
        build: .
        ports:
            - '5000:80'
        environment:
          - MOCK_API=true
        volumes:
            - "./app:/app/app"
        command: /start-reload.sh
