name: DAST

on: workflow_dispatch

jobs:
  zaproxy:
    name: zaproxy/dast
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'https://task-trackers-synchronizer.onrender.com'


