name: Manual tests

on: workflow_dispatch

jobs:
  zaproxy:
    name: zaproxy/dast
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'https://task-trackers-synchronizer.onrender.com'

  k6:
    name: k6/load
    runs-on: ubuntu-latest
    steps:
    - name: Run k6 load test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: k6.js