name: Manual tests

on: workflow_dispatch

jobs:
  k6:
    name: k6/load
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run k6 load test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6.js
